name: archPortal

services:
  # PostgreSQL database
  app-postgres:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5443:5432'
    networks:
      - backend
    volumes:
      - ./postgresql/data:/var/lib/postgresql
      - ./init-scripts/sql:/docker-entrypoint-initdb.d/

  # RabbitMQ
  app-rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    ports:
      - '5672:5672'   # AMQP
      - '15672:15672' # Management UI
    networks:
      - backend
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq

  # Keycloak MySQL DB
  idp-mysql:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'keycloak'
      MYSQL_USER: 'keycloak'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3307:3306'
    networks:
      - backend
    volumes:
      - ./idp_mysql_data:/var/lib/mysql

  # Keycloak
  idp-keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
      KC_DB: 'mysql'
      KC_DB_URL_HOST: 'idp-mysql'
      KC_DB_URL_DATABASE: 'keycloak'
      KC_DB_USERNAME: 'keycloak'
      KC_DB_PASSWORD: 'password'
      KC_PROXY: 'edge'
      KC_HOSTNAME: 'localhost'
      KC_HTTP_RELATIVE_PATH: '/auth'
      KC_HOSTNAME_DEBUG: 'true'
    command: 
      - start-dev
      - --import-realm
    ports:
      - '8180:8080'
    depends_on:
      - idp-mysql
    networks:
      - backend
    volumes:
      - ./keycloak/ArchPortal-export:/opt/keycloak/data/import


  # Redis (Boardgame cache & session store)
  # boardgame-redis:
  #   image: redis:7.2-alpine
  #   ports:
  #     - '6380:6379'
  #   networks:
  #     - backend
  #   volumes:
  #     - ./redis/data:/data

  game-postgres:
    image: postgres:17.1-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ttt
    networks:
      - backend
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./init-scripts/game_sql:/docker-entrypoint-initdb.d/
    ports:
      - "5444:5432"
  
  # Platform Backend
  platform-backend:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team15/archportal/archportalbackend/backend:latest
    depends_on:
      - idp-keycloak
    networks:
      - backend
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_MAIL_PASSWORD: roec zbxc douq fjdl
      SPRING_MAIL_USERNAME: archportalplatform@gmail.com

  # Platform Frontend
  platform-frontend:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team15/archportal/archportalfrontend/frontend:latest
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - backend

  # TicTacToe Backend
  tictactoe-backend:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team15/games/tik-tak-toe/ttt-backend/backend:latest
    networks:
      - backend
    ports:
      - '8081:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://game-postgres:5432/ttt
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
      LAUNCHER_API_URL: http://archportal-platform-backend-1:8080
      AI_SERVICE_URL: http://34.79.40.150/ai-player/move

  # TicTacToe Frontend
  tictactoe-frontend:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team15/games/tik-tak-toe/ttt-frontend/frontend:latest
    networks:
      - backend
    depends_on:
      - tictactoe-backend

  # # Checkers Backend
  # checkers-backend:
  #   image: alpine:3.20 # TODO: replace with checkers backend image
  #   depends_on:
  #     - boardgame_redis
  #     - app_rabbitmq
  #   networks:
  #     - backend

  # # Checkers Frontend
  # checkers-frontend:
  #   image: nginx:stable-alpine # TODO: replace with checkers frontend image
  #   ports:
  #     - '3002:80'
  #   networks:
  #     - backend
  #   depends_on:
  #     - checkers_backend

  # # Anti Corruption Layer
  # anticorruptionlayer:
  #   image: alpine:3.20 # TODO: replace with ACL image
  #   networks:
  #     - backend
  #   depends_on:
  #     - platform_backend
  #     - tictactoe_backend
  #     - checkers_backend

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped

    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    environment:
      TZ: "Europe/Brussels"

      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - backend

networks:
  # kc:
  #   name: kc-network
  #   driver: bridge
  backend:
    name: back-network
    driver: bridge
